# Generated by Django 2.1.15 on 2019-12-13 10:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(default='', max_length=100, verbose_name='Province')),
                ('city', models.CharField(default='', max_length=100, verbose_name='City')),
                ('district', models.CharField(default='', max_length=100, verbose_name='Ditrict')),
                ('address', models.CharField(default='', max_length=100, verbose_name='Address')),
                ('signer_name', models.CharField(default='', max_length=100, verbose_name='Signer')),
                ('signer_mobile', models.CharField(default='', max_length=11, verbose_name='Mobile')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='Add Time')),
            ],
            options={
                'verbose_name': 'Shipping Address',
                'verbose_name_plural': 'Shipping Address',
            },
        ),
        migrations.CreateModel(
            name='UserFav',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='Add Time')),
            ],
            options={
                'verbose_name': 'User Favourite',
                'verbose_name_plural': 'User Favourite',
            },
        ),
        migrations.CreateModel(
            name='UserLeavingMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.IntegerField(choices=[(1, 'Notes'), (2, 'Complain'), (3, 'Enquire'), (4, 'Support'), (5, 'Buy')], default=1, help_text='Types: 1(Notes),2(Complain),3(Enquire),4(Support),5(Buy)', verbose_name='Message Type')),
                ('subject', models.CharField(default='', max_length=100, verbose_name='Subject')),
                ('message', models.TextField(default='', help_text='Message Content', verbose_name='Message Content')),
                ('file', models.FileField(help_text='Upload File', upload_to='message/images/', verbose_name='Upload File')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='Add Time')),
            ],
            options={
                'verbose_name': 'User Leaving Message',
                'verbose_name_plural': 'User Leaving Message',
            },
        ),
    ]
