# Generated by Django 2.1.15 on 2019-12-13 10:45

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderGoods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_num', models.IntegerField(default=0, verbose_name='Quantity of Goods')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='Add Time')),
            ],
            options={
                'verbose_name': 'Order Details',
                'verbose_name_plural': 'Order Details',
            },
        ),
        migrations.CreateModel(
            name='OrderInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_sn', models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='Order Serial Number')),
                ('trade_no', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Trade Number')),
                ('pay_status', models.CharField(choices=[('TRADE_SUCCESS', 'Success'), ('TRADE_CLOSED', 'Closed'), ('WAIT_BUYER_PAY', 'Start_Trade'), ('TRADE_FINISHED', 'Close_Trade'), ('PAYING', 'Paying')], default='paying', max_length=30, verbose_name='Order Status')),
                ('post_script', models.CharField(max_length=200, verbose_name='Notes')),
                ('order_mount', models.FloatField(default=0.0, verbose_name='Order Amount')),
                ('pay_time', models.DateTimeField(blank=True, null=True, verbose_name='Paying Time')),
                ('address', models.CharField(default='', max_length=100, verbose_name='Shipping Address')),
                ('signer_name', models.CharField(default='', max_length=20, verbose_name='Signer')),
                ('singer_mobile', models.CharField(max_length=11, verbose_name='Signer Mobile')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='Add Time')),
            ],
            options={
                'verbose_name': '订单',
                'verbose_name_plural': '订单',
            },
        ),
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_num', models.IntegerField(default=0, verbose_name='Quantity')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='Add Time')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.Goods', verbose_name='Goods')),
            ],
            options={
                'verbose_name': 'Shopping Cart',
                'verbose_name_plural': 'Shopping Cart',
            },
        ),
    ]
