# Generated by Django 2.1.15 on 2020-02-04 01:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0004_auto_20200204_0140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Add Time'),
        ),
    ]
