# Generated by Django 2.1.15 on 2020-02-04 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0005_auto_20200204_0153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderinfo',
            name='add_time',
        ),
    ]
