# Generated by Django 2.1.15 on 2020-02-04 02:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0006_remove_orderinfo_add_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderinfo',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Add Time'),
        ),
    ]
