# Generated by Django 2.1.15 on 2019-12-13 10:45

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='banner', verbose_name='banner Image')),
                ('index', models.IntegerField(default=0, verbose_name='Order of Image')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='Add Time')),
            ],
            options={
                'verbose_name': 'Banner Images',
                'verbose_name_plural': 'Banner Images',
            },
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_sn', models.CharField(default='', max_length=50, verbose_name='Goods Serial Name')),
                ('name', models.CharField(max_length=100, verbose_name='Goods Name')),
                ('click_num', models.IntegerField(default=0, verbose_name='Click Number')),
                ('sold_num', models.IntegerField(default=0, verbose_name='Goods Sold Number')),
                ('fav_num', models.IntegerField(default=0, verbose_name='Favourite Number')),
                ('goods_num', models.IntegerField(default=0, verbose_name='Goods In Stock')),
                ('market_price', models.FloatField(default=0, verbose_name='Maket Price')),
                ('shop_price', models.FloatField(default=0, verbose_name='Current Price')),
                ('goods_brief', models.TextField(max_length=500, verbose_name='Goods Brif Description')),
                ('goods_desc', models.TextField(default='', verbose_name='Goods Details')),
                ('ship_free', models.BooleanField(default=True, verbose_name='Is Ship Free')),
                ('goods_front_image', models.ImageField(blank=True, null=True, upload_to='goods/images/', verbose_name='Cover Image')),
                ('is_new', models.BooleanField(default=False, verbose_name='Is Latest')),
                ('is_hot', models.BooleanField(default=False, verbose_name='Is Hot')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='Add Time')),
            ],
            options={
                'verbose_name': 'Goods',
                'verbose_name_plural': 'Goods',
            },
        ),
        migrations.CreateModel(
            name='GoodsCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', help_text='Category Name', max_length=30, verbose_name='Category Name')),
                ('code', models.CharField(default='', help_text='Category Code', max_length=30, verbose_name='Category Code')),
                ('desc', models.TextField(default='', help_text='Category Description', verbose_name='Category Description')),
                ('category_type', models.IntegerField(choices=[(1, 'First Category'), (2, 'Second Category'), (3, 'Third Category')], help_text='Category Type', verbose_name='Category Type')),
                ('is_tab', models.BooleanField(default=False, help_text='Is Navigated', verbose_name='isNav')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='Add Time')),
                ('parent_category', models.ForeignKey(blank=True, help_text='Parent Category', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Sub_Category', to='goods.GoodsCategory', verbose_name='Parent Category')),
            ],
            options={
                'verbose_name': 'Goods Category',
                'verbose_name_plural': 'Goods Category',
            },
        ),
        migrations.CreateModel(
            name='GoodsCategoryBrand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', help_text='Brand Name', max_length=30, verbose_name='Brand Name')),
                ('desc', models.TextField(default='', help_text='Brand Description', max_length=200, verbose_name='Brand Description')),
                ('image', models.ImageField(max_length=200, upload_to='brand/images')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='Add Time')),
            ],
            options={
                'verbose_name': 'Brand',
                'verbose_name_plural': 'Brand',
            },
        ),
        migrations.CreateModel(
            name='GoodsImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='goods/images/')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='Add Time')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='goods.Goods', verbose_name='Goods Image')),
            ],
            options={
                'verbose_name': 'Product Images',
                'verbose_name_plural': 'Product Images',
            },
        ),
        migrations.AddField(
            model_name='goods',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.GoodsCategory', verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='banner',
            name='goods',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.Goods', verbose_name='Goods'),
        ),
    ]
