# Generated by Django 2.1.15 on 2020-02-05 01:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0006_auto_20200131_1241'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotSearchWords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keywords', models.CharField(default='', max_length=20, verbose_name='Hot Keywords')),
                ('index', models.IntegerField(default=0, verbose_name='Order Of Keywords')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='Add Time')),
            ],
            options={
                'verbose_name': 'Hot Search Keywords',
                'verbose_name_plural': 'Hot Search Keywords',
            },
        ),
    ]
